using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace Bidwarss.Editor
{
    // Applies Assets/Bidwarss/Data/ItemCatalog.json (generated by Tools/market.py) to ItemCatalog assets:
    // titles, base value, per-condition dollar ranges, selection weights and condition weights.
    // Models (visualPrefab) the user already assigned to an item key are preserved.
    public static class CatalogSync
    {
        public const string DataPath = "Assets/Bidwarss/Data/ItemCatalog.json";
        [Serializable] sealed class ConditionData { public string name; public int weight; }
        [Serializable] sealed class ItemData
        {
            public string key, title, owned, color, shape;
            public int baseDollars, collector, selectionWeight, maxGroups;
            public int[] minDollars, maxDollars;
        }
        [Serializable] sealed class CatalogData { public int version; public ConditionData[] conditions; public ItemData[] items; }

        public static bool Available => AssetDatabase.LoadAssetAtPath<TextAsset>(DataPath) != null || File.Exists(DataPath);

        static CatalogData Load()
        {
            var asset = AssetDatabase.LoadAssetAtPath<TextAsset>(DataPath);
            string json = asset != null ? asset.text : File.ReadAllText(DataPath);
            var data = JsonUtility.FromJson<CatalogData>(json);
            if (data == null || data.items == null || data.items.Length == 0)
                throw new InvalidOperationException("Piyasa katalogu okunamadi: " + DataPath);
            return data;
        }

        public static void Apply(ItemCatalog catalog)
        {
            var data = Load();
            var previous = (catalog.entries ?? new ItemCatalog.Entry[0])
                .Where(e => e != null && !string.IsNullOrEmpty(e.key))
                .GroupBy(e => e.key).ToDictionary(g => g.Key, g => g.First());
            catalog.entries = data.items.Select(item =>
            {
                previous.TryGetValue(item.key, out var old);
                Color color;
                if (!ColorUtility.TryParseHtmlString(item.color, out color)) color = Color.white;
                ItemCatalog.SampleShape shape;
                if (!Enum.TryParse<ItemCatalog.SampleShape>(item.shape, out shape)) shape = ItemCatalog.SampleShape.Box;
                return new ItemCatalog.Entry
                {
                    key = item.key, title = item.title, owned = item.owned, baseDollars = item.baseDollars, collector = item.collector,
                    selectionWeight = item.selectionWeight, maxGroups = item.maxGroups,
                    minDollars = (int[])item.minDollars.Clone(), maxDollars = (int[])item.maxDollars.Clone(),
                    color = color, sampleShape = shape, visualPrefab = old != null ? old.visualPrefab : null
                };
            }).ToArray();
            if (data.conditions != null && catalog.conditions != null && data.conditions.Length == catalog.conditions.Length)
                for (int i = 0; i < data.conditions.Length; i++) catalog.conditions[i].weight = data.conditions[i].weight;
            // Fail here, with a readable message, rather than when a player presses Oda Kur.
            catalog.CreateRules(10, 12).Validate();
            EditorUtility.SetDirty(catalog);
        }

        [MenuItem("Bidwarss/Sync Market Catalog")]
        public static void SyncAll()
        {
            if (EditorApplication.isPlaying) return;
            if (!Available) { Debug.LogError("Bulunamadi: " + DataPath); return; }
            var guids = AssetDatabase.FindAssets("t:ItemCatalog");
            if (guids.Length == 0) { Debug.LogError("ItemCatalog asset'i yok. Once Bidwarss > Create Gameplay Scene calistir."); return; }
            foreach (string guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                var catalog = AssetDatabase.LoadAssetAtPath<ItemCatalog>(path);
                if (catalog == null) continue;
                Apply(catalog);
                Debug.Log("Bidwarss: piyasa katalogu guncellendi: " + path + " (" + catalog.entries.Length + " esya). Leaderboard rules hash (10 kasa / 12 istif): " + catalog.CreateRules(10, 12).Fingerprint());
            }
            AssetDatabase.SaveAssets();
        }

        public static void SyncBatch() => SyncAll();
    }
}
